import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  asideBar: false,
  cinemaHalls: [
    {
      hallName: "hall 1",
      seats: [
        [
          { row: 1, column: 1, status: "empty" },
          { row: 1, column: 2, status: "vip" },
          { row: 1, column: 3, status: "vip" },
          { row: 1, column: 4, status: "vip" },
          { row: 1, column: 5, status: "vip" },
          { row: 1, column: 6, status: "empty" },
          { row: 1, column: 7, status: "empty" },
          { row: 1, column: 8, status: "empty" },
          { row: 1, column: 9, status: "empty" },
          { row: 1, column: 10, status: "vip" },
          { row: 1, column: 11, status: "vip" },
          { row: 1, column: 12, status: "vip" },
          { row: 1, column: 13, status: "vip" },
          { row: 1, column: 14, status: "empty" },
          { row: 1, column: 15, status: "empty" },
          { row: 1, column: 16, status: "empty" },
          { row: 1, column: 17, status: "empty" },
          { row: 1, column: 18, status: "vip" },
          { row: 1, column: 19, status: "vip" },
          { row: 1, column: 20, status: "vip" },
          { row: 1, column: 21, status: "vip" },
          { row: 1, column: 22, status: "empty" },
        ],
        [
          { row: 2, column: 1, status: "vip" },
          { row: 2, column: 2, status: "vip" },
          { row: 2, column: 3, status: "vip" },
          { row: 2, column: 4, status: "vip" },
          { row: 2, column: 5, status: "vip" },
          { row: 2, column: 6, status: "vip" },
          { row: 2, column: 7, status: "empty" },
          { row: 2, column: 8, status: "empty" },
          { row: 2, column: 9, status: "vip" },
          { row: 2, column: 10, status: "vip" },
          { row: 2, column: 11, status: "vip" },
          { row: 2, column: 12, status: "vip" },
          { row: 2, column: 13, status: "vip" },
          { row: 2, column: 14, status: "vip" },
          { row: 2, column: 15, status: "empty" },
          { row: 2, column: 16, status: "empty" },
          { row: 2, column: 17, status: "vip" },
          { row: 2, column: 18, status: "vip" },
          { row: 2, column: 19, status: "vip" },
          { row: 2, column: 20, status: "vip" },
          { row: 2, column: 21, status: "vip" },
          { row: 2, column: 22, status: "vip" },
        ],
        [
          { row: 3, column: 1, status: "vip" },
          { row: 3, column: 2, status: "vip" },
          { row: 3, column: 3, status: "vip" },
          { row: 3, column: 4, status: "vip" },
          { row: 3, column: 5, status: "vip" },
          { row: 3, column: 6, status: "vip" },
          { row: 3, column: 7, status: "empty" },
          { row: 3, column: 8, status: "empty" },
          { row: 3, column: 9, status: "vip" },
          { row: 3, column: 10, status: "vip" },
          { row: 3, column: 11, status: "vip" },
          { row: 3, column: 12, status: "vip" },
          { row: 3, column: 13, status: "vip" },
          { row: 3, column: 14, status: "vip" },
          { row: 3, column: 15, status: "empty" },
          { row: 3, column: 16, status: "empty" },
          { row: 3, column: 17, status: "vip" },
          { row: 3, column: 18, status: "vip" },
          { row: 3, column: 19, status: "vip" },
          { row: 3, column: 20, status: "vip" },
          { row: 3, column: 21, status: "vip" },
          { row: 3, column: 22, status: "vip" },
        ],
        [
          { row: 4, column: 1, status: "booked" },
          { row: 4, column: 2, status: "booked" },
          { row: 4, column: 3, status: "booked" },
          { row: 4, column: 4, status: "booked" },
          { row: 4, column: 5, status: "booked" },
          { row: 4, column: 6, status: "booked" },
          { row: 4, column: 7, status: "empty" },
          { row: 4, column: 8, status: "empty" },
          { row: 4, column: 9, status: "booked" },
          { row: 4, column: 10, status: "booked" },
          { row: 4, column: 11, status: "booked" },
          { row: 4, column: 12, status: "booked" },
          { row: 4, column: 13, status: "booked" },
          { row: 4, column: 14, status: "booked" },
          { row: 4, column: 15, status: "empty" },
          { row: 4, column: 16, status: "empty" },
          { row: 4, column: 17, status: "booked" },
          { row: 4, column: 18, status: "booked" },
          { row: 4, column: 19, status: "booked" },
          { row: 4, column: 20, status: "booked" },
          { row: 4, column: 21, status: "booked" },
          { row: 4, column: 22, status: "booked" },
        ],
        [
          { row: 5, column: 1, status: "booked" },
          { row: 5, column: 2, status: "booked" },
          { row: 5, column: 3, status: "booked" },
          { row: 5, column: 4, status: "booked" },
          { row: 5, column: 5, status: "booked" },
          { row: 5, column: 6, status: "booked" },
          { row: 5, column: 7, status: "empty" },
          { row: 5, column: 8, status: "empty" },
          { row: 5, column: 9, status: "booked" },
          { row: 5, column: 10, status: "booked" },
          { row: 5, column: 11, status: "booked" },
          { row: 5, column: 12, status: "booked" },
          { row: 5, column: 13, status: "booked" },
          { row: 5, column: 14, status: "booked" },
          { row: 5, column: 15, status: "empty" },
          { row: 5, column: 16, status: "empty" },
          { row: 5, column: 17, status: "available" },
          { row: 5, column: 18, status: "booked" },
          { row: 5, column: 19, status: "booked" },
          { row: 5, column: 20, status: "booked" },
          { row: 5, column: 21, status: "booked" },
          { row: 5, column: 22, status: "booked" },
        ],
        [
          { row: 6, column: 1, status: "available" },
          { row: 6, column: 2, status: "available" },
          { row: 6, column: 3, status: "available" },
          { row: 6, column: 4, status: "available" },
          { row: 6, column: 5, status: "available" },
          { row: 6, column: 6, status: "available" },
          { row: 6, column: 7, status: "empty" },
          { row: 6, column: 8, status: "empty" },
          { row: 6, column: 9, status: "available" },
          { row: 6, column: 10, status: "available" },
          { row: 6, column: 11, status: "available" },
          { row: 6, column: 12, status: "available" },
          { row: 6, column: 13, status: "available" },
          { row: 6, column: 14, status: "available" },
          { row: 6, column: 15, status: "empty" },
          { row: 6, column: 16, status: "empty" },
          { row: 6, column: 17, status: "available" },
          { row: 6, column: 18, status: "available" },
          { row: 6, column: 19, status: "available" },
          { row: 6, column: 20, status: "available" },
          { row: 6, column: 21, status: "available" },
          { row: 6, column: 22, status: "available" },
        ],
        [
          { row: 7, column: 1, status: "available" },
          { row: 7, column: 2, status: "available" },
          { row: 7, column: 3, status: "available" },
          { row: 7, column: 4, status: "available" },
          { row: 7, column: 5, status: "available" },
          { row: 7, column: 6, status: "available" },
          { row: 7, column: 7, status: "empty" },
          { row: 7, column: 8, status: "empty" },
          { row: 7, column: 9, status: "available" },
          { row: 7, column: 10, status: "available" },
          { row: 7, column: 11, status: "available" },
          { row: 7, column: 12, status: "available" },
          { row: 7, column: 13, status: "available" },
          { row: 7, column: 14, status: "available" },
          { row: 7, column: 15, status: "empty" },
          { row: 7, column: 16, status: "empty" },
          { row: 7, column: 17, status: "available" },
          { row: 7, column: 18, status: "available" },
          { row: 7, column: 19, status: "available" },
          { row: 7, column: 20, status: "available" },
          { row: 7, column: 21, status: "available" },
          { row: 7, column: 22, status: "available" },
        ],
        [
          { row: 8, column: 1, status: "available" },
          { row: 8, column: 2, status: "available" },
          { row: 8, column: 3, status: "available" },
          { row: 8, column: 4, status: "available" },
          { row: 8, column: 5, status: "available" },
          { row: 8, column: 6, status: "available" },
          { row: 8, column: 7, status: "empty" },
          { row: 8, column: 8, status: "empty" },
          { row: 8, column: 9, status: "available" },
          { row: 8, column: 10, status: "available" },
          { row: 8, column: 11, status: "available" },
          { row: 8, column: 12, status: "available" },
          { row: 8, column: 13, status: "available" },
          { row: 8, column: 14, status: "available" },
          { row: 8, column: 15, status: "empty" },
          { row: 8, column: 16, status: "empty" },
          { row: 8, column: 17, status: "available" },
          { row: 8, column: 18, status: "available" },
          { row: 8, column: 19, status: "available" },
          { row: 8, column: 20, status: "available" },
          { row: 8, column: 21, status: "available" },
          { row: 8, column: 22, status: "available" },
        ],
        [
          { row: 9, column: 1, status: "available" },
          { row: 9, column: 2, status: "available" },
          { row: 9, column: 3, status: "available" },
          { row: 9, column: 4, status: "available" },
          { row: 9, column: 5, status: "available" },
          { row: 9, column: 6, status: "available" },
          { row: 9, column: 7, status: "empty" },
          { row: 9, column: 8, status: "empty" },
          { row: 9, column: 9, status: "available" },
          { row: 9, column: 10, status: "available" },
          { row: 9, column: 11, status: "available" },
          { row: 9, column: 12, status: "available" },
          { row: 9, column: 13, status: "available" },
          { row: 9, column: 14, status: "available" },
          { row: 9, column: 15, status: "empty" },
          { row: 9, column: 16, status: "empty" },
          { row: 9, column: 17, status: "available" },
          { row: 9, column: 18, status: "available" },
          { row: 9, column: 19, status: "available" },
          { row: 9, column: 20, status: "available" },
          { row: 9, column: 21, status: "available" },
          { row: 9, column: 22, status: "available" },
        ],
        [
          { row: 10, column: 1, status: "available" },
          { row: 10, column: 2, status: "available" },
          { row: 10, column: 3, status: "available" },
          { row: 10, column: 4, status: "available" },
          { row: 10, column: 5, status: "available" },
          { row: 10, column: 6, status: "available" },
          { row: 10, column: 7, status: "empty" },
          { row: 10, column: 8, status: "empty" },
          { row: 10, column: 9, status: "available" },
          { row: 10, column: 10, status: "available" },
          { row: 10, column: 11, status: "available" },
          { row: 10, column: 12, status: "available" },
          { row: 10, column: 13, status: "available" },
          { row: 10, column: 14, status: "available" },
          { row: 10, column: 15, status: "empty" },
          { row: 10, column: 16, status: "empty" },
          { row: 10, column: 17, status: "available" },
          { row: 10, column: 18, status: "available" },
          { row: 10, column: 19, status: "available" },
          { row: 10, column: 20, status: "available" },
          { row: 10, column: 21, status: "available" },
          { row: 10, column: 22, status: "available" },
        ],
      ],
    },
    {
      hallName: "hall 2",
      seats: [
        [
          { row: 1, column: 1, status: "empty" },
          { row: 1, column: 2, status: "vip" },
          { row: 1, column: 3, status: "vip" },
          { row: 1, column: 4, status: "vip" },
          { row: 1, column: 5, status: "vip" },
          { row: 1, column: 6, status: "empty" },
          { row: 1, column: 7, status: "empty" },
          { row: 1, column: 8, status: "empty" },
          { row: 1, column: 9, status: "empty" },
          { row: 1, column: 10, status: "vip" },
          { row: 1, column: 11, status: "vip" },
          { row: 1, column: 12, status: "vip" },
          { row: 1, column: 13, status: "vip" },
          { row: 1, column: 14, status: "empty" },
          { row: 1, column: 15, status: "empty" },
          { row: 1, column: 16, status: "empty" },
          // { row: 1, column: 17, status: "empty" },
          // { row: 1, column: 18, status: "vip" },
          // { row: 1, column: 19, status: "vip" },
          // { row: 1, column: 20, status: "vip" },
          // { row: 1, column: 21, status: "vip" },
          // { row: 1, column: 22, status: "empty" },
        ],
        [
          { row: 2, column: 1, status: "vip" },
          { row: 2, column: 2, status: "vip" },
          { row: 2, column: 3, status: "vip" },
          { row: 2, column: 4, status: "vip" },
          { row: 2, column: 5, status: "vip" },
          { row: 2, column: 6, status: "vip" },
          { row: 2, column: 7, status: "empty" },
          { row: 2, column: 8, status: "empty" },
          { row: 2, column: 9, status: "vip" },
          { row: 2, column: 10, status: "vip" },
          { row: 2, column: 11, status: "vip" },
          { row: 2, column: 12, status: "vip" },
          { row: 2, column: 13, status: "vip" },
          { row: 2, column: 14, status: "vip" },
          { row: 2, column: 15, status: "empty" },
          { row: 2, column: 16, status: "empty" },
          // { row: 2, column: 17, status: "vip" },
          // { row: 2, column: 18, status: "vip" },
          // { row: 2, column: 19, status: "vip" },
          // { row: 2, column: 20, status: "vip" },
          // { row: 2, column: 21, status: "vip" },
          // { row: 2, column: 22, status: "vip" },
        ],
        [
          { row: 3, column: 1, status: "vip" },
          { row: 3, column: 2, status: "vip" },
          { row: 3, column: 3, status: "vip" },
          { row: 3, column: 4, status: "vip" },
          { row: 3, column: 5, status: "vip" },
          { row: 3, column: 6, status: "vip" },
          { row: 3, column: 7, status: "empty" },
          { row: 3, column: 8, status: "empty" },
          { row: 3, column: 9, status: "vip" },
          { row: 3, column: 10, status: "vip" },
          { row: 3, column: 11, status: "vip" },
          { row: 3, column: 12, status: "vip" },
          { row: 3, column: 13, status: "vip" },
          { row: 3, column: 14, status: "vip" },
          { row: 3, column: 15, status: "empty" },
          { row: 3, column: 16, status: "empty" },
          // { row: 3, column: 17, status: "vip" },
          // { row: 3, column: 18, status: "vip" },
          // { row: 3, column: 19, status: "vip" },
          // { row: 3, column: 20, status: "vip" },
          // { row: 3, column: 21, status: "vip" },
          // { row: 3, column: 22, status: "vip" },
        ],
        [
          { row: 4, column: 1, status: "booked" },
          { row: 4, column: 2, status: "booked" },
          { row: 4, column: 3, status: "booked" },
          { row: 4, column: 4, status: "booked" },
          { row: 4, column: 5, status: "booked" },
          { row: 4, column: 6, status: "booked" },
          { row: 4, column: 7, status: "empty" },
          { row: 4, column: 8, status: "empty" },
          { row: 4, column: 9, status: "booked" },
          { row: 4, column: 10, status: "booked" },
          { row: 4, column: 11, status: "booked" },
          { row: 4, column: 12, status: "booked" },
          { row: 4, column: 13, status: "booked" },
          { row: 4, column: 14, status: "booked" },
          { row: 4, column: 15, status: "empty" },
          { row: 4, column: 16, status: "empty" },
          // { row: 4, column: 17, status: "booked" },
          // { row: 4, column: 18, status: "booked" },
          // { row: 4, column: 19, status: "booked" },
          // { row: 4, column: 20, status: "booked" },
          // { row: 4, column: 21, status: "booked" },
          // { row: 4, column: 22, status: "booked" },
        ],
        [
          { row: 5, column: 1, status: "booked" },
          { row: 5, column: 2, status: "booked" },
          { row: 5, column: 3, status: "booked" },
          { row: 5, column: 4, status: "booked" },
          { row: 5, column: 5, status: "booked" },
          { row: 5, column: 6, status: "booked" },
          { row: 5, column: 7, status: "empty" },
          { row: 5, column: 8, status: "empty" },
          { row: 5, column: 9, status: "booked" },
          { row: 5, column: 10, status: "booked" },
          { row: 5, column: 11, status: "booked" },
          { row: 5, column: 12, status: "booked" },
          { row: 5, column: 13, status: "booked" },
          { row: 5, column: 14, status: "booked" },
          { row: 5, column: 15, status: "empty" },
          { row: 5, column: 16, status: "empty" },
          // { row: 5, column: 17, status: "available" },
          // { row: 5, column: 18, status: "booked" },
          // { row: 5, column: 19, status: "booked" },
          // { row: 5, column: 20, status: "booked" },
          // { row: 5, column: 21, status: "booked" },
          // { row: 5, column: 22, status: "booked" },
        ],
        [
          { row: 6, column: 1, status: "available" },
          { row: 6, column: 2, status: "available" },
          { row: 6, column: 3, status: "available" },
          { row: 6, column: 4, status: "available" },
          { row: 6, column: 5, status: "available" },
          { row: 6, column: 6, status: "available" },
          { row: 6, column: 7, status: "empty" },
          { row: 6, column: 8, status: "empty" },
          { row: 6, column: 9, status: "available" },
          { row: 6, column: 10, status: "available" },
          { row: 6, column: 11, status: "available" },
          { row: 6, column: 12, status: "available" },
          { row: 6, column: 13, status: "available" },
          { row: 6, column: 14, status: "available" },
          { row: 6, column: 15, status: "empty" },
          { row: 6, column: 16, status: "empty" },
          // { row: 6, column: 17, status: "available" },
          // { row: 6, column: 18, status: "available" },
          // { row: 6, column: 19, status: "available" },
          // { row: 6, column: 20, status: "available" },
          // { row: 6, column: 21, status: "available" },
          // { row: 6, column: 22, status: "available" },
        ],
        [
          { row: 7, column: 1, status: "available" },
          { row: 7, column: 2, status: "available" },
          { row: 7, column: 3, status: "available" },
          { row: 7, column: 4, status: "available" },
          { row: 7, column: 5, status: "available" },
          { row: 7, column: 6, status: "available" },
          { row: 7, column: 7, status: "empty" },
          { row: 7, column: 8, status: "empty" },
          { row: 7, column: 9, status: "available" },
          { row: 7, column: 10, status: "available" },
          { row: 7, column: 11, status: "available" },
          { row: 7, column: 12, status: "available" },
          { row: 7, column: 13, status: "available" },
          { row: 7, column: 14, status: "available" },
          { row: 7, column: 15, status: "empty" },
          { row: 7, column: 16, status: "empty" },
          // { row: 7, column: 17, status: "available" },
          // { row: 7, column: 18, status: "available" },
          // { row: 7, column: 19, status: "available" },
          // { row: 7, column: 20, status: "available" },
          // { row: 7, column: 21, status: "available" },
          // { row: 7, column: 22, status: "available" },
        ],
        [
          { row: 8, column: 1, status: "available" },
          { row: 8, column: 2, status: "available" },
          { row: 8, column: 3, status: "available" },
          { row: 8, column: 4, status: "available" },
          { row: 8, column: 5, status: "available" },
          { row: 8, column: 6, status: "available" },
          { row: 8, column: 7, status: "empty" },
          { row: 8, column: 8, status: "empty" },
          { row: 8, column: 9, status: "available" },
          { row: 8, column: 10, status: "available" },
          { row: 8, column: 11, status: "available" },
          { row: 8, column: 12, status: "available" },
          { row: 8, column: 13, status: "available" },
          { row: 8, column: 14, status: "available" },
          { row: 8, column: 15, status: "empty" },
          { row: 8, column: 16, status: "empty" },
          // { row: 8, column: 17, status: "available" },
          // { row: 8, column: 18, status: "available" },
          // { row: 8, column: 19, status: "available" },
          // { row: 8, column: 20, status: "available" },
          // { row: 8, column: 21, status: "available" },
          // { row: 8, column: 22, status: "available" },
        ],
        [
          { row: 9, column: 1, status: "available" },
          { row: 9, column: 2, status: "available" },
          { row: 9, column: 3, status: "available" },
          { row: 9, column: 4, status: "available" },
          { row: 9, column: 5, status: "available" },
          { row: 9, column: 6, status: "available" },
          { row: 9, column: 7, status: "empty" },
          { row: 9, column: 8, status: "empty" },
          { row: 9, column: 9, status: "available" },
          { row: 9, column: 10, status: "available" },
          { row: 9, column: 11, status: "available" },
          { row: 9, column: 12, status: "available" },
          { row: 9, column: 13, status: "available" },
          { row: 9, column: 14, status: "available" },
          { row: 9, column: 15, status: "empty" },
          { row: 9, column: 16, status: "empty" },
          // { row: 9, column: 17, status: "available" },
          // { row: 9, column: 18, status: "available" },
          // { row: 9, column: 19, status: "available" },
          // { row: 9, column: 20, status: "available" },
          // { row: 9, column: 21, status: "available" },
          // { row: 9, column: 22, status: "available" },
        ],
        [
          { row: 10, column: 1, status: "available" },
          { row: 10, column: 2, status: "available" },
          { row: 10, column: 3, status: "available" },
          { row: 10, column: 4, status: "available" },
          { row: 10, column: 5, status: "available" },
          { row: 10, column: 6, status: "available" },
          { row: 10, column: 7, status: "empty" },
          { row: 10, column: 8, status: "empty" },
          { row: 10, column: 9, status: "available" },
          { row: 10, column: 10, status: "available" },
          { row: 10, column: 11, status: "available" },
          { row: 10, column: 12, status: "available" },
          { row: 10, column: 13, status: "available" },
          { row: 10, column: 14, status: "available" },
          { row: 10, column: 15, status: "empty" },
          { row: 10, column: 16, status: "empty" },
          // { row: 10, column: 17, status: "available" },
          // { row: 10, column: 18, status: "available" },
          // { row: 10, column: 19, status: "available" },
          // { row: 10, column: 20, status: "available" },
          // { row: 10, column: 21, status: "available" },
          // { row: 10, column: 22, status: "available" },
        ],
      ],
    },
  ],
};

export const appSlice = createSlice({
  name: "app",
  initialState,
  reducers: {
    setAsideBar: (state) => {
      state.asideBar = !state.asideBar;
    },

    setNewHall: (state, action) => {
      state.cinemaHalls.push(action.payload);
    },
  },
});

export const { setAsideBar, setNewHall } = appSlice.actions;
export default appSlice.reducer;
